"""Background job metadata primitives for armactl web."""

from __future__ import annotations

from armactl.web.jobs.models import (
    JOB_STATUS_CANCELLED,
    JOB_STATUS_FAILED,
    JOB_STATUS_QUEUED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_SUCCEEDED,
    JobRecord,
)
from armactl.web.jobs.runner import (
    JobContext,
    JobDispatcher,
    JobDispatchResult,
    JobHandlerResult,
    JobRunnerError,
    create_default_dispatcher,
    dispatch_job,
    enqueue_job,
)
from armactl.web.jobs.server import (
    SERVER_INSTALL_JOB_KIND,
    SERVER_REPAIR_JOB_KIND,
    SERVER_UPDATE_JOB_KIND,
    create_server_job_dispatcher,
    dispatch_server_job,
    enqueue_server_install,
    enqueue_server_repair,
    enqueue_server_update,
    handle_server_install,
    handle_server_repair,
    handle_server_update,
    start_server_job_worker,
)
from armactl.web.jobs.store import (
    JobNotFoundError,
    JobStoreError,
    JobTransitionError,
    append_job_output,
    cancel_job,
    create_job,
    get_active_job,
    get_job,
    list_recent_jobs,
    mark_job_failed,
    mark_job_running,
    mark_job_succeeded,
)

__all__ = [
    "SERVER_INSTALL_JOB_KIND",
    "SERVER_REPAIR_JOB_KIND",
    "SERVER_UPDATE_JOB_KIND",
    "create_server_job_dispatcher",
    "dispatch_server_job",
    "enqueue_server_install",
    "enqueue_server_repair",
    "enqueue_server_update",
    "handle_server_install",
    "handle_server_repair",
    "handle_server_update",
    "start_server_job_worker",
    "JOB_STATUS_CANCELLED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_QUEUED",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_SUCCEEDED",
    "JobContext",
    "JobDispatchResult",
    "JobDispatcher",
    "JobHandlerResult",
    "JobNotFoundError",
    "JobRunnerError",
    "JobRecord",
    "JobStoreError",
    "JobTransitionError",
    "append_job_output",
    "create_default_dispatcher",
    "cancel_job",
    "create_job",
    "dispatch_job",
    "enqueue_job",
    "get_job",
    "get_active_job",
    "list_recent_jobs",
    "mark_job_failed",
    "mark_job_running",
    "mark_job_succeeded",
]
