"""Public facade for the web file browser service.

The implementation is split by responsibility into filesystem_* modules. This
module intentionally contains only compatibility re-exports for older imports.
"""

from __future__ import annotations

from armactl.web.services.file_replacements import (
    MAX_REPLACEMENT_BYTES,
    ReplacedFile,
    StagedReplacement,
    cleanup_staged_replacement,
    is_replacement_candidate,
    replace_file_and_audit,
)
from armactl.web.services.filesystem_errors import (
    DownloadUnavailableError,
    FileBrowserError,
    InvalidUploadFilenameError,
    PathUnavailableError,
    ReplacementInvalidContentError,
    ReplacementTooLargeError,
    ReplacementUnavailableError,
    RootUnavailableError,
    UnknownFileRootError,
    UnsafeFilePathError,
    UploadTargetExistsError,
    UploadTooLargeError,
    UploadUnavailableError,
)
from armactl.web.services.filesystem_listing import (
    PREVIEW_TEXT_FILENAMES,
    PREVIEW_TEXT_SUFFIXES,
    Breadcrumb,
    DirectoryListing,
    FileMetadata,
    get_file_metadata,
    is_preview_candidate,
    list_directory,
)
from armactl.web.services.filesystem_paths import (
    FORBIDDEN_PATH_NAMES,
    ResolvedBrowserPath,
    parent_relative_path,
    resolve_browser_path,
)
from armactl.web.services.filesystem_preview import (
    MAX_PREVIEW_BYTES,
    FilePreview,
    preview_text_file,
    redact_preview_text,
)
from armactl.web.services.filesystem_roots import (
    ROOT_DEFINITIONS,
    UPLOAD_ROOT_IDS,
    FileRoot,
    RootDefinition,
    get_file_root,
    list_allowed_roots,
    root_allows_upload,
)
from armactl.web.services.filesystem_transfer import (
    MAX_UPLOAD_BYTES,
    DownloadFile,
    StagedUpload,
    UploadedFile,
    cleanup_staged_upload,
    cleanup_staged_upload_path,
    publish_staged_upload,
    resolve_download_file,
    safe_download_filename,
    safe_upload_filename,
    stage_upload_file,
    upload_file,
)

__all__ = [
    "FORBIDDEN_PATH_NAMES",
    "MAX_PREVIEW_BYTES",
    "MAX_REPLACEMENT_BYTES",
    "MAX_UPLOAD_BYTES",
    "PREVIEW_TEXT_FILENAMES",
    "PREVIEW_TEXT_SUFFIXES",
    "ROOT_DEFINITIONS",
    "UPLOAD_ROOT_IDS",
    "Breadcrumb",
    "DirectoryListing",
    "DownloadFile",
    "DownloadUnavailableError",
    "FileBrowserError",
    "FileMetadata",
    "FilePreview",
    "FileRoot",
    "InvalidUploadFilenameError",
    "PathUnavailableError",
    "ReplacedFile",
    "ReplacementInvalidContentError",
    "ReplacementTooLargeError",
    "ReplacementUnavailableError",
    "ResolvedBrowserPath",
    "RootDefinition",
    "RootUnavailableError",
    "StagedReplacement",
    "StagedUpload",
    "UnknownFileRootError",
    "UnsafeFilePathError",
    "UploadTargetExistsError",
    "UploadTooLargeError",
    "UploadUnavailableError",
    "UploadedFile",
    "cleanup_staged_replacement",
    "cleanup_staged_upload",
    "cleanup_staged_upload_path",
    "get_file_metadata",
    "get_file_root",
    "is_preview_candidate",
    "is_replacement_candidate",
    "list_allowed_roots",
    "list_directory",
    "parent_relative_path",
    "preview_text_file",
    "publish_staged_upload",
    "redact_preview_text",
    "replace_file_and_audit",
    "resolve_browser_path",
    "resolve_download_file",
    "root_allows_upload",
    "safe_download_filename",
    "safe_upload_filename",
    "stage_upload_file",
    "upload_file",
]
