"""Controlled web actions for Arma Workshop mods."""

from __future__ import annotations

import json
import tempfile
from dataclasses import dataclass, field, replace
from pathlib import Path
from typing import Any, BinaryIO

from armactl import discovery, mods_manager, paths
from armactl.addon_cleanup import CleanupResult, cleanup_unconfigured_addons
from armactl.config_manager import ConfigError
from armactl.redaction import redact_sensitive_text
from armactl.web.services import mutation_recovery, pending_work
from armactl.web.services.audit import AuditLogError, append_audit_event

ACTION_ADD = "mod.add"
ACTION_UPDATE = "mod.update"
ACTION_DISABLE = "mod.disable"
ACTION_ENABLE = "mod.enable"
ACTION_REMOVE = "mod.remove"
ACTION_BULK_ADD = "mod.bulk-add"
ACTION_IMPORT = "mod.import"
ACTION_EXPORT = "mod.export"
ACTION_DEDUPE = "mod.dedupe"
ACTION_CLEANUP_CHECK = "mod.cleanup-check"
ACTION_CLEANUP = "mod.cleanup"
IMPORT_MODE_APPEND = "append"
IMPORT_MODE_REPLACE = "replace"
SINGLE_MOD_ACTIONS = frozenset(
    {
        ACTION_ADD,
        ACTION_DISABLE,
        ACTION_ENABLE,
        ACTION_REMOVE,
    }
)
SUPPORTED_ACTIONS = frozenset(
    {
        *SINGLE_MOD_ACTIONS,
        ACTION_BULK_ADD,
        ACTION_IMPORT,
        ACTION_EXPORT,
        ACTION_DEDUPE,
        ACTION_CLEANUP_CHECK,
        ACTION_CLEANUP,
    }
)
MAX_MOD_TEXT_LENGTH = 256
MAX_IMPORT_BYTES = 1024 * 1024
MAX_AUDIT_IDS = 10
MAX_CLEANUP_SUMMARY_ENTRIES = 8
MOD_PARTIAL_FAILURE_MESSAGE = (
    "Mod action did not complete cleanly after changing mod state. "
    "Review the current mod list and pending restart work before retrying."
)
MOD_CLEANUP_PARTIAL_FAILURE_MESSAGE = (
    "Mod cleanup did not complete cleanly after changing addon files. "
    "Review the cleanup recovery manifest before retrying."
)
MOD_UNEXPECTED_FAILURE_MESSAGE = "Mod action failed before completing."


class ModActionError(ValueError):
    """Raised when a mod action request is invalid."""


@dataclass(frozen=True)
class ModActionResult:
    """Safe result for rendering and audit logging."""

    action: str
    instance: str
    target: str
    success: bool
    changed: bool
    message: str
    exit_code: int
    restart_required: bool = True
    audit_written: bool = True
    intent_audited: bool = True
    backend_success: bool | None = None
    backend_message: str = ""
    pending_work_warning: str = ""
    pending_work_error: str = ""
    details: dict[str, object] = field(default_factory=dict)

    @property
    def status_label(self) -> str:
        return "success" if self.success else "failure"


@dataclass(frozen=True)
class ModExportDownload:
    """Safe JSON download generated by an audited mod export action."""

    result: ModActionResult
    filename: str = "armactl-mod-pack.json"
    content: bytes = b""


def normalize_mod_action(action: str) -> str:
    """Normalize a user-facing mod action name."""
    return action.strip().lower()


def is_supported_action(action: str) -> bool:
    """Return whether the action is a known mod action."""
    return normalize_mod_action(action) in SUPPORTED_ACTIONS


def confirmation_failure(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    target: str = "",
) -> ModActionResult:
    """Return a controlled failure for missing remove confirmation."""
    return ModActionResult(
        action=ACTION_REMOVE,
        instance=instance,
        target=_safe_text(target),
        success=False,
        changed=False,
        message="Confirmation is required to remove this mod.",
        exit_code=1,
        audit_written=False,
    )


def cleanup_confirmation_failure(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> ModActionResult:
    """Return a controlled failure for missing addon cleanup confirmation."""
    return ModActionResult(
        action=ACTION_CLEANUP,
        instance=instance or paths.DEFAULT_INSTANCE_NAME,
        target="unused addons",
        success=False,
        changed=False,
        message="Confirmation is required to clean up unused addons.",
        exit_code=1,
        restart_required=False,
        audit_written=False,
    )


def _safe_text(value: object, *, max_length: int = 500) -> str:
    redacted = redact_sensitive_text(value).replace("\r", " ").replace("\n", " ").strip()
    if len(redacted) > max_length:
        return f"{redacted[:max_length]}..."
    return redacted


def _mod_target_label(reference: str, name: object = "") -> str:
    safe_reference = _safe_text(reference, max_length=64).upper()
    safe_name = _safe_text(name, max_length=128)
    if safe_name:
        return f"{safe_name} ({safe_reference})"
    return safe_reference


def _validated_optional_text(value: Any, *, message: str) -> str:
    text = str(value or "").strip()
    if len(text) > MAX_MOD_TEXT_LENGTH or any(ord(char) < 32 for char in text):
        raise ModActionError(message)
    return text


def _fingerprint_mod_entry(mod: object) -> dict[str, str]:
    if not isinstance(mod, dict):
        return {"modId": _safe_text(mod, max_length=64).upper(), "name": "", "version": ""}
    return {
        "modId": _safe_text(mod.get("modId"), max_length=64).upper(),
        "name": _safe_text(mod.get("name"), max_length=128),
        "version": _safe_text(mod.get("version"), max_length=64),
    }


def _sorted_mod_fingerprint_entries(mods: list[dict[str, Any]]) -> list[dict[str, str]]:
    entries = [_fingerprint_mod_entry(mod) for mod in mods]
    return sorted(entries, key=lambda item: (item["modId"], item["name"], item["version"]))


def _mods_restart_fingerprint(config_path: Path) -> str:
    active_mods = mods_manager.get_mods(config_path)
    disabled_mods = mods_manager.get_disabled_mods(config_path)
    return pending_work.safe_state_fingerprint(
        {
            "active": _sorted_mod_fingerprint_entries(active_mods),
            "disabled": _sorted_mod_fingerprint_entries(disabled_mods),
        }
    )


def _safe_mods_restart_fingerprint(config_path: Path) -> str:
    try:
        return _mods_restart_fingerprint(config_path)
    except Exception:  # noqa: BLE001 - pending tracking falls back to action-only.
        return ""


def _mod_id(value: Any) -> str:
    return mods_manager.require_valid_mod_id(value)


def _mod_name_from_entries(mods: list[dict[str, Any]], reference: str) -> str:
    for mod in mods:
        if not isinstance(mod, dict):
            continue
        try:
            entry_id = _mod_id(mod.get("modId"))
        except ConfigError:
            continue
        if entry_id == reference:
            return _safe_text(mod.get("name"), max_length=128)
    return ""


def _existing_mod_name(
    config_path: Path,
    reference: str,
    *,
    active: bool = True,
    disabled: bool = True,
) -> str:
    try:
        if active:
            name = _mod_name_from_entries(mods_manager.get_mods(config_path), reference)
            if name:
                return name
        if disabled:
            return _mod_name_from_entries(
                mods_manager.get_disabled_mods(config_path),
                reference,
            )
    except (ConfigError, OSError, TypeError, ValueError):
        return ""
    return ""


def _config_path(instance: str) -> Path:
    try:
        state = discovery.discover(instance=instance, save=False)
    except Exception as exc:  # noqa: BLE001 - discovery preflight fails closed.
        raise ModActionError("Server config path is unavailable.") from exc
    if not state.config_path:
        raise ModActionError("Server config path is unavailable.")
    return Path(state.config_path)


def _result(
    *,
    action: str,
    instance: str,
    target: str,
    success: bool,
    changed: bool,
    message: str,
    exit_code: int,
    details: dict[str, object] | None = None,
) -> ModActionResult:
    return ModActionResult(
        action=action,
        instance=instance,
        target=_safe_text(target),
        success=success,
        changed=changed,
        message=_safe_text(message),
        exit_code=exit_code,
        details=details or {},
    )


def _failure(
    *,
    action: str,
    instance: str,
    target: str,
    message: object,
) -> ModActionResult:
    return _result(
        action=action,
        instance=instance,
        target=target,
        success=False,
        changed=False,
        message=_safe_text(message),
        exit_code=1,
    )


def _cleanup_details(result: mods_manager.ModUpdateResult) -> dict[str, object]:
    details: dict[str, object] = {}
    removed_ids = sorted(result.removed_ids)
    if removed_ids:
        details["removed_ids"] = removed_ids[:MAX_AUDIT_IDS]
        details["removed_id_count"] = str(len(removed_ids))
    cleanup = result.cleanup_result
    if cleanup is not None:
        details.update(_cleanup_result_details(cleanup))
    if result.enospc_retry_performed:
        details["enospc_retry_performed"] = "yes"
    return details


def _cleanup_result_details(cleanup: CleanupResult) -> dict[str, object]:
    return {
        "cleanup_deleted_count": str(len(cleanup.deleted)),
        "cleanup_skipped_count": str(len(cleanup.skipped)),
        "cleanup_error_count": str(len(cleanup.errors)),
        "cleanup_freed": cleanup.freed_display,
        **_cleanup_manifest_details(cleanup),
    }


def _cleanup_manifest_details(cleanup: CleanupResult) -> dict[str, object]:
    manifests = cleanup.manifests
    if not manifests:
        return {}
    return {
        "cleanup_recovery_handles": [manifest.name for manifest in manifests],
        "cleanup_manifest_count": str(len(manifests)),
        "cleanup_manifest_planned_delete_count": str(
            sum(manifest.planned_delete_count for manifest in manifests)
        ),
        "cleanup_manifest_deleted_count": str(
            sum(manifest.completed_delete_count for manifest in manifests)
        ),
        "cleanup_manifest_failed_count": str(
            sum(manifest.failed_delete_count for manifest in manifests)
        ),
        "cleanup_manifest_skipped_count": str(
            sum(manifest.skipped_count for manifest in manifests)
        ),
    }


def _cleanup_recovery_note(cleanup: CleanupResult | None) -> str:
    if cleanup is None or not cleanup.manifests:
        return ""
    handles = [manifest.name for manifest in cleanup.manifests]
    if len(handles) == 1:
        return f"Recovery manifest: {handles[0]}."
    shown = ", ".join(handles[:3])
    omitted = len(handles) - 3
    if omitted > 0:
        return f"Recovery manifests: {shown}; {omitted} more."
    return f"Recovery manifests: {shown}."


def _with_cleanup_recovery_note(message: str, cleanup: CleanupResult | None) -> str:
    note = _cleanup_recovery_note(cleanup)
    return f"{message} {note}" if note else message


def _cleanup_error_count(cleanup: CleanupResult | None) -> int:
    return len(cleanup.errors) if cleanup is not None else 0


def _cleanup_partial_message(prefix: str, cleanup: CleanupResult | None) -> str:
    errors = _cleanup_error_count(cleanup)
    message = f"{prefix}, but addon cleanup reported {errors} error(s)."
    return _with_cleanup_recovery_note(message, cleanup)


def _cleanup_partial_exception_result(
    *,
    action: str,
    instance: str,
    target: str,
    error: mods_manager.ModCleanupPartialError,
) -> ModActionResult:
    cleanup = error.cleanup_result
    details: dict[str, object] = {
        "backend_error_class": _safe_text(error.__class__.__name__, max_length=80),
        **_cleanup_result_details(cleanup),
    }
    recovery_note = _cleanup_recovery_note(cleanup)
    if recovery_note:
        details["recovery"] = recovery_note.rstrip(".")
    if error.restart_required:
        details["pending_details"] = _safe_text(target)

    return ModActionResult(
        action=action,
        instance=instance,
        target=_safe_text(target),
        success=False,
        changed=error.changed,
        message=(
            MOD_CLEANUP_PARTIAL_FAILURE_MESSAGE
            if error.changed
            else MOD_UNEXPECTED_FAILURE_MESSAGE
        ),
        exit_code=1,
        restart_required=error.restart_required,
        backend_success=False,
        backend_message="Addon cleanup did not complete cleanly.",
        details=details,
    )


def _safe_cleanup_entry_name(path: Path) -> str:
    safe_name = _safe_text(Path(path).name or "unknown", max_length=96)
    lowered = safe_name.lower()
    for marker in ("token=", "token:", "password=", "password:"):
        marker_start = lowered.find(marker)
        if marker_start >= 0:
            marker_end = marker_start + len(marker)
            return f"{safe_name[:marker_end]}***"
    return safe_name


def _bounded_cleanup_entry_names(entries: list[Path]) -> list[str]:
    return [_safe_cleanup_entry_name(entry) for entry in entries[:MAX_CLEANUP_SUMMARY_ENTRIES]]


def _cleanup_entry_word(count: int) -> str:
    return "entry" if count == 1 else "entries"


def _cleanup_omitted_count(entries: list[Path]) -> str:
    return str(max(0, len(entries) - MAX_CLEANUP_SUMMARY_ENTRIES))


def _summary_message(prefix: str, counts: dict[str, int]) -> str:
    return (
        f"{prefix}: "
        f"added {counts.get('added', 0)}, "
        f"updated {counts.get('updated', 0)}, "
        f"reactivated {counts.get('reactivated', 0)}, "
        f"unchanged {counts.get('unchanged', 0)}, "
        f"duplicate input {counts.get('duplicate_input', 0)}."
    )


def _bulk_add_details(result: mods_manager.BulkModAddResult) -> dict[str, object]:
    ids = [item.mod_id for item in result.items]
    return {
        "added": str(result.added_count),
        "updated": str(result.updated_count),
        "reactivated": str(result.reactivated_count),
        "unchanged": str(result.unchanged_count),
        "duplicate_input": str(result.duplicate_input_count),
        "requested_id_count": str(len(result.items)),
        "changed_count": str(result.changed_count),
        "active_count": str(result.active_count),
        "ids": ids[:MAX_AUDIT_IDS],
    }


def _import_details(
    *,
    mode: str,
    added_count: int,
    skipped_count: int,
    update_result: mods_manager.ModUpdateResult,
) -> dict[str, object]:
    return {
        "mode": mode,
        "added": str(added_count),
        "skipped": str(skipped_count),
        **_cleanup_details(update_result),
    }


def _normalize_import_mode(value: object) -> str:
    mode = str(value or "").strip().lower()
    if mode in {"", IMPORT_MODE_APPEND}:
        return IMPORT_MODE_APPEND
    if mode == IMPORT_MODE_REPLACE:
        return IMPORT_MODE_REPLACE
    raise ModActionError("Import mode is invalid.")


def import_replace_confirmation_failure(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> ModActionResult:
    """Return a controlled failure for missing replace confirmation."""
    return ModActionResult(
        action=ACTION_IMPORT,
        instance=instance or paths.DEFAULT_INSTANCE_NAME,
        target="replace import",
        success=False,
        changed=False,
        message="Confirmation is required to replace the current mod list.",
        exit_code=1,
        audit_written=False,
    )


def missing_import_file_failure(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> ModActionResult:
    """Return a controlled failure for a missing import upload."""
    return ModActionResult(
        action=ACTION_IMPORT,
        instance=instance or paths.DEFAULT_INSTANCE_NAME,
        target="mod pack import",
        success=False,
        changed=False,
        message="A JSON mod pack file is required.",
        exit_code=1,
        audit_written=False,
    )


def _read_import_upload(upload_file: BinaryIO) -> bytes:
    try:
        payload = upload_file.read(MAX_IMPORT_BYTES + 1)
    except OSError as error:
        raise ModActionError("Import file could not be read.") from error
    if isinstance(payload, str):
        payload = payload.encode("utf-8")
    if len(payload) > MAX_IMPORT_BYTES:
        raise ModActionError("Import file is too large.")
    if not payload.strip():
        raise ModActionError("Import file is empty.")
    return payload


def _import_mods_from_upload(
    *,
    config_path: Path,
    upload_file: BinaryIO,
    data_root: Path,
    append: bool,
) -> tuple[int, int, mods_manager.ModUpdateResult]:
    payload = _read_import_upload(upload_file)
    temp_root = Path(data_root) / "web" / "tmp"
    temp_root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="mod-import-", dir=temp_root) as temp_dir:
        import_path = Path(temp_dir) / "mod-pack.json"
        import_path.write_bytes(payload)
        return mods_manager.import_mods_detailed(
            config_path,
            import_path,
            append=append,
        )


def bulk_add_mods(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    text: str,
) -> ModActionResult:
    """Add multiple Workshop mods parsed by mods_manager from pasted text."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    target = "bulk mod add"
    try:
        requested_ids = mods_manager.extract_mod_ids(str(text or ""))
        if not requested_ids:
            raise ConfigError("At least one valid Mod ID is required.")
        config_path = _config_path(normalized_instance)
        result = mods_manager.add_mods_detailed(config_path, requested_ids)
    except (ModActionError, ConfigError) as error:
        return _failure(
            action=ACTION_BULK_ADD,
            instance=normalized_instance,
            target=target,
            message=error,
        )

    counts = {
        "added": result.added_count,
        "updated": result.updated_count,
        "reactivated": result.reactivated_count,
        "unchanged": result.unchanged_count,
        "duplicate_input": result.duplicate_input_count,
    }
    return _result(
        action=ACTION_BULK_ADD,
        instance=normalized_instance,
        target=f"{len(requested_ids)} extracted mod ID(s)",
        success=True,
        changed=result.changed_count > 0,
        message=_summary_message("Bulk add complete", counts),
        exit_code=0,
        details={
            **_bulk_add_details(result),
            "pending_details": f"{result.changed_count} mod add/update change(s)",
        },
    )


def import_mod_pack(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    upload_file: BinaryIO,
    data_root: Path,
    mode: str = IMPORT_MODE_APPEND,
) -> ModActionResult:
    """Import a JSON mod pack or full config through mods_manager."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        normalized_mode = _normalize_import_mode(mode)
        append = normalized_mode == IMPORT_MODE_APPEND
        config_path = _config_path(normalized_instance)
        added_count, skipped_count, update_result = _import_mods_from_upload(
            config_path=config_path,
            upload_file=upload_file,
            data_root=data_root,
            append=append,
        )
    except mods_manager.ModCleanupPartialError as error:
        return _cleanup_partial_exception_result(
            action=ACTION_IMPORT,
            instance=normalized_instance,
            target="mod pack import",
            error=error,
        )
    except (ModActionError, ConfigError, OSError) as error:
        return _failure(
            action=ACTION_IMPORT,
            instance=normalized_instance,
            target="mod pack import",
            message=error,
        )

    target = f"{normalized_mode} import"
    cleanup = update_result.cleanup_result
    cleanup_errors = _cleanup_error_count(cleanup)
    success = cleanup_errors == 0
    return _result(
        action=ACTION_IMPORT,
        instance=normalized_instance,
        target=target,
        success=success,
        changed=update_result.config_changed,
        message=(
            f"Import {normalized_mode} complete: "
            f"added {added_count}, skipped {skipped_count}."
            if success
            else _cleanup_partial_message(f"Import {normalized_mode} changed mod state", cleanup)
        ),
        exit_code=0 if success else 1,
        details={
            **_import_details(
                mode=normalized_mode,
                added_count=added_count,
                skipped_count=skipped_count,
                update_result=update_result,
            ),
            "pending_details": target,
        },
    )


def dedupe_mods(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> ModActionResult:
    """Remove duplicate active/disabled mods through mods_manager."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        config_path = _config_path(normalized_instance)
        duplicate_count = mods_manager.dedupe_mods(config_path)
    except (ModActionError, ConfigError) as error:
        return _failure(
            action=ACTION_DEDUPE,
            instance=normalized_instance,
            target="dedupe mods",
            message=error,
        )

    changed = duplicate_count > 0
    return _result(
        action=ACTION_DEDUPE,
        instance=normalized_instance,
        target="dedupe mods",
        success=True,
        changed=changed,
        message=(
            f"Removed {duplicate_count} duplicate mod(s)."
            if changed
            else "No duplicate mods found."
        ),
        exit_code=0,
        details={
            "duplicate_removed_count": str(duplicate_count),
            "pending_details": f"{duplicate_count} duplicate mod(s) removed",
        },
    )


def _addon_cleanup_details(
    cleanup: CleanupResult,
    *,
    dry_run: bool,
) -> dict[str, object]:
    details = {
        "cleanup_skipped_count": str(len(cleanup.skipped)),
        "cleanup_error_count": str(len(cleanup.errors)),
        "cleanup_freed": cleanup.freed_display,
    }
    if dry_run:
        details["cleanup_candidate_count"] = str(len(cleanup.deleted))
        summary_key = "cleanup_candidate_summary"
    else:
        details["cleanup_deleted_count"] = str(len(cleanup.deleted))
        summary_key = "cleanup_deleted_summary"

    summary = _bounded_cleanup_entry_names(cleanup.deleted)
    if summary:
        details[summary_key] = summary
        omitted = _cleanup_omitted_count(cleanup.deleted)
        if omitted != "0":
            details[f"{summary_key}_omitted_count"] = omitted

    skipped_summary = _bounded_cleanup_entry_names(cleanup.skipped)
    if skipped_summary:
        details["cleanup_skipped_summary"] = skipped_summary
        omitted = _cleanup_omitted_count(cleanup.skipped)
        if omitted != "0":
            details["cleanup_skipped_summary_omitted_count"] = omitted

    if cleanup.errors:
        details["cleanup_error_summary"] = (
            "Path-specific cleanup errors were suppressed from web output."
        )
    details.update(_cleanup_manifest_details(cleanup))
    return details


def _addon_cleanup_message(cleanup: CleanupResult, *, dry_run: bool) -> tuple[bool, str]:
    found = len(cleanup.deleted)
    errors = len(cleanup.errors)
    entry_word = _cleanup_entry_word(found)
    if dry_run:
        if errors:
            return False, f"Cleanup check found {errors} warning(s); no files were deleted."
        if found == 0:
            return True, "No unused addon files found."
        return (
            True,
            f"Found {found} unused addon {entry_word}; "
            f"cleanup would free {cleanup.freed_display}.",
        )

    if errors and found:
        return (
            False,
            _with_cleanup_recovery_note(
                f"Cleanup completed with {errors} error(s); deleted {found} addon "
                f"{entry_word}, freed {cleanup.freed_display}.",
                cleanup,
            ),
        )
    if errors:
        return (
            False,
            _with_cleanup_recovery_note(
                f"Cleanup failed with {errors} error(s); no addon files were deleted.",
                cleanup,
            ),
        )
    if found == 0:
        return True, "No unused addon files found."
    return (
        True,
        _with_cleanup_recovery_note(
            f"Deleted {found} unused addon {entry_word}, freed {cleanup.freed_display}.",
            cleanup,
        ),
    )


def _run_unused_addon_cleanup(
    *,
    instance: str,
    dry_run: bool,
) -> ModActionResult:
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        config_path = _config_path(normalized_instance)
        cleanup = cleanup_unconfigured_addons(
            config_path,
            dry_run=dry_run,
            manifest_instance=normalized_instance,
        )
    except (ModActionError, ConfigError, OSError, TypeError, ValueError):
        return _failure(
            action=ACTION_CLEANUP_CHECK if dry_run else ACTION_CLEANUP,
            instance=normalized_instance,
            target="unused addons",
            message="Addon cleanup is unavailable.",
        )

    success, message = _addon_cleanup_message(cleanup, dry_run=dry_run)
    return _result(
        action=ACTION_CLEANUP_CHECK if dry_run else ACTION_CLEANUP,
        instance=normalized_instance,
        target="unused addons",
        success=success,
        changed=False if dry_run else bool(cleanup.deleted),
        message=message,
        exit_code=0 if success else 1,
        details=_addon_cleanup_details(cleanup, dry_run=dry_run),
    )


def check_unused_addons(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> ModActionResult:
    """Dry-run unused addon cleanup without auditing or deleting files."""
    return replace(
        _run_unused_addon_cleanup(instance=instance, dry_run=True),
        restart_required=False,
    )


def cleanup_unused_addons(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> ModActionResult:
    """Clean unused local addon files without changing config state."""
    return replace(
        _run_unused_addon_cleanup(instance=instance, dry_run=False),
        restart_required=False,
    )


def export_active_mods_json(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
) -> tuple[ModActionResult, bytes]:
    """Return active mods as exported JSON without writing an export file."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        config_path = _config_path(normalized_instance)
        active_mods = mods_manager.get_mods(config_path)
    except (ModActionError, ConfigError) as error:
        return (
            _failure(
                action=ACTION_EXPORT,
                instance=normalized_instance,
                target="active mods export",
                message=error,
            ),
            b"",
        )

    content = (json.dumps(active_mods, indent=4) + "\n").encode("utf-8")
    return (
        _result(
            action=ACTION_EXPORT,
            instance=normalized_instance,
            target="active mods export",
            success=True,
            changed=False,
            message=f"Exported {len(active_mods)} active mod(s).",
            exit_code=0,
            details={"exported_count": str(len(active_mods))},
        ),
        content,
    )


def add_or_update_mod(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    mod_id: str,
    name: str = "",
    version: str = "",
) -> ModActionResult:
    """Add, update, or reactivate one Workshop mod through mods_manager."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        reference = _mod_id(mod_id)
        mod_name = _validated_optional_text(name, message="Mod name is invalid.")
        mod_version = _validated_optional_text(version, message="Mod version is invalid.")
        config_path = _config_path(normalized_instance)
        target_label = _mod_target_label(
            reference,
            mod_name or _existing_mod_name(config_path, reference),
        )
        result = mods_manager.add_mod_detailed(
            config_path,
            reference,
            mod_name,
            mod_version,
        )
    except (ModActionError, ConfigError) as error:
        return _failure(
            action=ACTION_ADD,
            instance=normalized_instance,
            target=mod_id,
            message=error,
        )

    if result.status == "added":
        return _result(
            action=ACTION_ADD,
            instance=normalized_instance,
            target=reference,
            success=True,
            changed=True,
            message="Mod added.",
            exit_code=0,
            details={"mod_label": target_label},
        )
    if result.status == "updated":
        return _result(
            action=ACTION_UPDATE,
            instance=normalized_instance,
            target=reference,
            success=True,
            changed=True,
            message="Mod updated.",
            exit_code=0,
            details={"mod_label": target_label},
        )
    if result.status == "reactivated":
        return _result(
            action=ACTION_ENABLE,
            instance=normalized_instance,
            target=reference,
            success=True,
            changed=True,
            message="Mod enabled.",
            exit_code=0,
            details={"mod_label": target_label},
        )
    return _result(
        action=ACTION_ADD,
        instance=normalized_instance,
        target=reference,
        success=True,
        changed=False,
        message="Mod was unchanged.",
        exit_code=0,
        details={"mod_label": target_label},
    )


def disable_mod(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    mod_id: str,
) -> ModActionResult:
    """Disable one active Workshop mod through mods_manager."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        reference = _mod_id(mod_id)
        config_path = _config_path(normalized_instance)
        target_label = _mod_target_label(
            reference,
            _existing_mod_name(config_path, reference, disabled=False),
        )
        changed = mods_manager.disable_mod(config_path, reference)
    except (ModActionError, ConfigError) as error:
        return _failure(
            action=ACTION_DISABLE,
            instance=normalized_instance,
            target=mod_id,
            message=error,
        )

    return _result(
        action=ACTION_DISABLE,
        instance=normalized_instance,
        target=reference,
        success=True,
        changed=changed,
        message="Mod disabled." if changed else "Mod was unchanged.",
        exit_code=0,
        details={"mod_label": target_label},
    )


def enable_mod(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    mod_id: str,
) -> ModActionResult:
    """Enable one disabled Workshop mod through mods_manager."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        reference = _mod_id(mod_id)
        config_path = _config_path(normalized_instance)
        target_label = _mod_target_label(
            reference,
            _existing_mod_name(config_path, reference, active=False),
        )
        changed = mods_manager.enable_mod(config_path, reference)
    except (ModActionError, ConfigError) as error:
        return _failure(
            action=ACTION_ENABLE,
            instance=normalized_instance,
            target=mod_id,
            message=error,
        )

    return _result(
        action=ACTION_ENABLE,
        instance=normalized_instance,
        target=reference,
        success=True,
        changed=changed,
        message="Mod enabled." if changed else "Mod was unchanged.",
        exit_code=0,
        details={"mod_label": target_label},
    )


def remove_mod(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    mod_id: str,
) -> ModActionResult:
    """Remove one active or disabled Workshop mod through mods_manager."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    try:
        reference = _mod_id(mod_id)
        config_path = _config_path(normalized_instance)
        target_label = _mod_target_label(
            reference,
            _existing_mod_name(config_path, reference),
        )
        result = mods_manager.remove_mod_detailed(
            config_path,
            reference,
            manifest_instance=normalized_instance,
        )
    except mods_manager.ModCleanupPartialError as error:
        return _cleanup_partial_exception_result(
            action=ACTION_REMOVE,
            instance=normalized_instance,
            target=mod_id,
            error=error,
        )
    except (ModActionError, ConfigError) as error:
        return _failure(
            action=ACTION_REMOVE,
            instance=normalized_instance,
            target=mod_id,
            message=error,
        )

    cleanup = result.cleanup_result
    cleanup_errors = _cleanup_error_count(cleanup)
    success = cleanup_errors == 0
    if result.config_changed and not success:
        message = _cleanup_partial_message("Mod removed", cleanup)
    else:
        message = "Mod removed." if result.config_changed else "Mod was unchanged."

    return _result(
        action=ACTION_REMOVE,
        instance=normalized_instance,
        target=reference,
        success=success,
        changed=result.config_changed,
        message=message,
        exit_code=0 if success else 1,
        details={"mod_label": target_label, **_cleanup_details(result)},
    )


def run_mod_action(
    action: str,
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    mod_id: str = "",
    name: str = "",
    version: str = "",
) -> ModActionResult:
    """Run a controlled Workshop mod action without auditing."""
    normalized = normalize_mod_action(action)
    if normalized == ACTION_ADD:
        return add_or_update_mod(
            instance=instance,
            mod_id=mod_id,
            name=name,
            version=version,
        )
    if normalized == ACTION_DISABLE:
        return disable_mod(instance=instance, mod_id=mod_id)
    if normalized == ACTION_ENABLE:
        return enable_mod(instance=instance, mod_id=mod_id)
    if normalized == ACTION_REMOVE:
        return remove_mod(instance=instance, mod_id=mod_id)
    raise ModActionError("Unknown mod action.")


def _append_mod_action_intent(action, *, audit_log_path, username, instance, target):
    append_audit_event(
        audit_log_path,
        username=username,
        action=action,
        instance=instance,
        target=_safe_text(target),
        success=True,
        message="Mod action requested.",
        exit_code=0,
        details={"phase": "intent"},
    )


def _mod_intent_audit_failure(action, instance, target):
    return ModActionResult(
        action=action,
        instance=instance,
        target=_safe_text(target),
        success=False,
        changed=False,
        message="Mod action was not run because audit logging failed.",
        exit_code=1,
        audit_written=False,
        intent_audited=False,
        backend_success=False,
    )


def audit_mod_action_result(
    result: ModActionResult,
    *,
    audit_log_path: Path,
    username: str,
) -> ModActionResult:
    """Append an audit event for a Workshop mod action result."""
    details = {
        "phase": "outcome",
        "changed": "yes" if result.changed else "no",
        **result.details,
    }
    try:
        append_audit_event(
            audit_log_path,
            username=username,
            action=result.action,
            instance=result.instance,
            target=result.target,
            success=result.success,
            message=result.message,
            exit_code=result.exit_code,
            details=details,
        )
    except Exception:  # noqa: BLE001 - outcome audit runs after backend mutation.
        return replace(
            result,
            success=False,
            message="Mod action completed but audit logging failed.",
            exit_code=1,
            backend_success=result.success,
            backend_message=result.message,
            audit_written=False,
        )
    return result


def _pending_mod_details(result: ModActionResult) -> str:
    return str(
        result.details.get("pending_details")
        or result.details.get("mod_label")
        or result.target
    )


def _mark_restart_pending_for_mod_result(
    result: ModActionResult,
    *,
    db_path: Path | None,
    username: str,
    baseline_fingerprint: str = "",
) -> ModActionResult:
    if db_path is None or not result.changed or not result.restart_required:
        return result
    pending_details = _pending_mod_details(result)
    current_fingerprint = ""
    if baseline_fingerprint:
        try:
            current_fingerprint = _safe_mods_restart_fingerprint(
                _config_path(result.instance)
            )
        except ModActionError:
            current_fingerprint = ""

    write_result = mutation_recovery.mark_restart_pending_for_mutation(
        mutation_recovery.RestartPendingRecovery(
            db_path=db_path,
            instance=result.instance,
            kind=pending_work.KIND_MODS,
            source_action=result.action,
            source_path="/mods",
            title="Mod changes",
            username=username,
            details=pending_details,
            baseline_fingerprint=baseline_fingerprint,
            current_fingerprint=current_fingerprint,
        )
    )
    return replace(
        result,
        pending_work_warning=write_result.warning,
        pending_work_error=write_result.error,
    )


def _run_mod_workflow_and_audit(
    action: str,
    *,
    instance: str,
    target: str,
    audit_log_path: Path,
    username: str,
    db_path: Path | None = None,
    mark_pending_restart: bool = True,
    workflow,
) -> ModActionResult:
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    safe_target = _safe_text(target)
    try:
        _append_mod_action_intent(
            action,
            audit_log_path=audit_log_path,
            username=username,
            instance=normalized_instance,
            target=safe_target,
        )
    except AuditLogError:
        return _mod_intent_audit_failure(action, normalized_instance, safe_target)

    baseline_fingerprint = ""
    baseline_config_path: Path | None = None
    if db_path is not None and mark_pending_restart:
        try:
            baseline_config_path = _config_path(normalized_instance)
            baseline_fingerprint = _mods_restart_fingerprint(baseline_config_path)
        except (ModActionError, ConfigError):
            baseline_fingerprint = ""

    try:
        result = workflow()
    except Exception as exc:  # noqa: BLE001 - report controlled partial mutation state.
        state_changed_after_failure = False
        if baseline_fingerprint and baseline_config_path is not None:
            try:
                current_fingerprint = _mods_restart_fingerprint(baseline_config_path)
            except Exception:  # noqa: BLE001 - diagnostics must stay controlled.
                current_fingerprint = ""
            state_changed_after_failure = bool(
                current_fingerprint and current_fingerprint != baseline_fingerprint
            )

        cleanup = getattr(exc, "cleanup_result", None)
        cleanup_changed_after_failure = isinstance(cleanup, CleanupResult) and bool(
            cleanup.deleted
        )
        restart_required_after_failure = bool(
            state_changed_after_failure or getattr(exc, "restart_required", False)
        )
        changed_after_failure = bool(
            state_changed_after_failure
            or cleanup_changed_after_failure
            or getattr(exc, "changed", False)
        )

        details: dict[str, object] = {
            "backend_error_class": _safe_text(exc.__class__.__name__, max_length=80),
        }
        if isinstance(cleanup, CleanupResult):
            details.update(_cleanup_result_details(cleanup))
            recovery_note = _cleanup_recovery_note(cleanup)
            if recovery_note:
                details["recovery"] = recovery_note.rstrip(".")
        if restart_required_after_failure:
            details.update(
                {
                    "pending_details": safe_target,
                    "recovery": details.get("recovery")
                    or "Review the current mod list and pending restart work before retrying.",
                }
            )

        if restart_required_after_failure:
            message = MOD_PARTIAL_FAILURE_MESSAGE
        elif cleanup_changed_after_failure:
            message = MOD_CLEANUP_PARTIAL_FAILURE_MESSAGE
        else:
            message = MOD_UNEXPECTED_FAILURE_MESSAGE

        result = ModActionResult(
            action=action,
            instance=normalized_instance,
            target=safe_target,
            success=False,
            changed=changed_after_failure,
            message=message,
            exit_code=1,
            restart_required=restart_required_after_failure,
            backend_success=False,
            backend_message="Unexpected backend error.",
            details=details,
        )
    result = audit_mod_action_result(
        result,
        audit_log_path=audit_log_path,
        username=username,
    )
    if not mark_pending_restart:
        return result
    return _mark_restart_pending_for_mod_result(
        result,
        db_path=db_path,
        username=username,
        baseline_fingerprint=baseline_fingerprint,
    )


def run_mod_action_and_audit(
    action: str,
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    mod_id: str = "",
    name: str = "",
    version: str = "",
    audit_log_path: Path,
    username: str,
    db_path: Path | None = None,
) -> ModActionResult:
    """Run a Workshop mod action and append safe audit events."""
    normalized = normalize_mod_action(action)
    if normalized not in SINGLE_MOD_ACTIONS:
        raise ModActionError("Unknown mod action.")
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    return _run_mod_workflow_and_audit(
        normalized,
        instance=normalized_instance,
        target=mod_id,
        audit_log_path=audit_log_path,
        username=username,
        db_path=db_path,
        workflow=lambda: run_mod_action(
            normalized,
            instance=normalized_instance,
            mod_id=mod_id,
            name=name,
            version=version,
        ),
    )


def run_bulk_add_and_audit(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    text: str,
    audit_log_path: Path,
    username: str,
    db_path: Path | None = None,
) -> ModActionResult:
    """Audit and run a bulk add/paste mod workflow."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    return _run_mod_workflow_and_audit(
        ACTION_BULK_ADD,
        instance=normalized_instance,
        target="bulk mod add",
        audit_log_path=audit_log_path,
        username=username,
        db_path=db_path,
        workflow=lambda: bulk_add_mods(
            instance=normalized_instance,
            text=text,
        ),
    )


def run_import_mod_pack_and_audit(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    upload_file: BinaryIO,
    data_root: Path,
    mode: str = IMPORT_MODE_APPEND,
    audit_log_path: Path,
    username: str,
    db_path: Path | None = None,
) -> ModActionResult:
    """Audit and run a mod-pack import workflow."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    safe_mode = _safe_text(mode, max_length=32) or IMPORT_MODE_APPEND
    return _run_mod_workflow_and_audit(
        ACTION_IMPORT,
        instance=normalized_instance,
        target=f"{safe_mode} mod pack import",
        audit_log_path=audit_log_path,
        username=username,
        db_path=db_path,
        workflow=lambda: import_mod_pack(
            instance=normalized_instance,
            upload_file=upload_file,
            data_root=data_root,
            mode=mode,
        ),
    )


def run_dedupe_and_audit(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    audit_log_path: Path,
    username: str,
    db_path: Path | None = None,
) -> ModActionResult:
    """Audit and run duplicate mod cleanup."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    return _run_mod_workflow_and_audit(
        ACTION_DEDUPE,
        instance=normalized_instance,
        target="dedupe mods",
        audit_log_path=audit_log_path,
        username=username,
        db_path=db_path,
        workflow=lambda: dedupe_mods(instance=normalized_instance),
    )


def run_cleanup_unused_addons_and_audit(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    audit_log_path: Path,
    username: str,
) -> ModActionResult:
    """Audit and run cleanup for unused local Workshop addon files."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    return _run_mod_workflow_and_audit(
        ACTION_CLEANUP,
        instance=normalized_instance,
        target="unused addons",
        audit_log_path=audit_log_path,
        username=username,
        mark_pending_restart=False,
        workflow=lambda: cleanup_unused_addons(instance=normalized_instance),
    )


def export_mod_pack_and_audit(
    *,
    instance: str = paths.DEFAULT_INSTANCE_NAME,
    audit_log_path: Path,
    username: str,
) -> ModExportDownload:
    """Audit and return active mods as a JSON download."""
    normalized_instance = instance or paths.DEFAULT_INSTANCE_NAME
    content = b""

    def workflow() -> ModActionResult:
        nonlocal content
        result, content = export_active_mods_json(instance=normalized_instance)
        return result

    result = _run_mod_workflow_and_audit(
        ACTION_EXPORT,
        instance=normalized_instance,
        target="active mods export",
        audit_log_path=audit_log_path,
        username=username,
        mark_pending_restart=False,
        workflow=workflow,
    )
    if not result.success:
        content = b""
    return ModExportDownload(result=result, content=content)
